//
// NewArticle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NewArticle: Codable, Hashable {

    public var featured: Bool? = false
    public var title: String
    public var url: String
    public var imageUrl: String
    public var newsSite: String
    public var summary: String?
    public var publishedAt: String
    public var launches: [AnyCodable]?
    public var events: [AnyCodable]?

    public init(featured: Bool? = false, title: String, url: String, imageUrl: String, newsSite: String, summary: String? = nil, publishedAt: String, launches: [AnyCodable]? = nil, events: [AnyCodable]? = nil) {
        self.featured = featured
        self.title = title
        self.url = url
        self.imageUrl = imageUrl
        self.newsSite = newsSite
        self.summary = summary
        self.publishedAt = publishedAt
        self.launches = launches
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case featured
        case title
        case url
        case imageUrl
        case newsSite
        case summary
        case publishedAt
        case launches
        case events
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(featured, forKey: .featured)
        try container.encode(title, forKey: .title)
        try container.encode(url, forKey: .url)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(newsSite, forKey: .newsSite)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encode(publishedAt, forKey: .publishedAt)
        try container.encodeIfPresent(launches, forKey: .launches)
        try container.encodeIfPresent(events, forKey: .events)
    }
}

