//
// Report.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Report: Codable, Hashable, Identifiable {

    public var id: Int
    public var title: String?
    public var url: String?
    public var imageUrl: String?
    public var newsSite: String?
    public var summary: String?
    public var publishedAt: String?

    public init(id: Int, title: String? = nil, url: String? = nil, imageUrl: String? = nil, newsSite: String? = nil, summary: String? = nil, publishedAt: String? = nil) {
        self.id = id
        self.title = title
        self.url = url
        self.imageUrl = imageUrl
        self.newsSite = newsSite
        self.summary = summary
        self.publishedAt = publishedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case url
        case imageUrl
        case newsSite
        case summary
        case publishedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(newsSite, forKey: .newsSite)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(publishedAt, forKey: .publishedAt)
    }
}

